#+title: pabbrev - Predictive Abbreviation Expansions for Emacs
#+author: Phillip Lord
#+language: en
#+export_file_name: pabbrev.texi
#+texinfo_dir_category: Emacs convenience features
#+texinfo_dir_title: Pabbrev: (pabbrev).
#+texinfo_dir_desc: Predictive Abbreviations

#+html: <a href="https://www.gnu.org/software/emacs/"><img alt="GNU Emacs" src="https://img.shields.io/badge/Emacs-%237F5AB6.svg?&style=for-the-badge&logo=gnu-emacs&logoColor=white"
#+html: <a href="https://elpa.gnu.org/packages/pabbrev.html"><img alt="GNU ELPA" src="https://elpa.gnu.org/packages/pabbrev.svg"/></a>
#+html: <a href="https://melpa.org/packages/pabbrev"><img alt="MELPA" src="https://melpa.org/packages/pabbrev-badge.svg"/></a>

Pabbrev provides predictive abbreviation expansion with no configuration needed
and works with any mode.

Pabbrev is a small package, which analyzes buffer text in the buffer and
collects usage statistics to rank most used words highest. Pabbrev is
un-intrusive and out of the way. It does not provide any user interface on its
own other than TAB-based insertion on demand. Pabbrev can be used with Emacs
completion facilities and packages such as Companry or Corfu, for the user
interaction and user interface.

For more details see pabbrev.el

* Features

- Timer-based auto-suggestions (does not block main user-interface)
- In-buffer color-coded display of best candidate
- Suggestions by usage frequency or shortest-prefix
- The current candidate is inserted with =TAB=
- List of all available suggestions

* Installation and Configuration

Pabbrev is available from [[https://elpa.gnu.org/packages/corfu.html][GNU ELPA]]. You can install it directly via
~package-install~.

To enable pabbrev in your Emacs, run =M-x global-pabbrev-mode=.

* Key bindings

Pabbrev bind keybindings in pabbrev-mode-map, and currently only binds
<TAB> key to pabbrev-expand-maybe function.

* Contributions

All non-significant contributions to this package require a copyright assignment
to the FSF.



